NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/docs

AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /api/v1
