AppBundle\Character\Command\CreateCharacterCommand:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: Uuid
        prototype:
            expose: true
            type: string
