AppBundle\Turn\Command\CreateTurnCommand:
    properties:
        id:
            - NotBlank: ~
            - Type: Ramsey\Uuid\UuidInterface
        tile:
            - NotBlank: ~
            - Type: AppBundle\World\TileInterface
